### ISSUE TITLE
Split webpack bundle.js into 3rd party code and our code. 

### ISSUE THREAD

**Issue by ohall** [GRT/onesie#16]
Split webpack bundle.js into 3rd party bundle and our bundle. 

https://github.com/webpack/docs/wiki/list-of-plugins#commonschunkplugin

**Comment by tjsampson** [comment]
@ohall [This pull request](https://github.com/GRT/onesie/pull/49) covers this issue.

**Comment by tjsampson** [comment]
@ohall Closing this issue. Smoke tested [onesie on github](http://grt.github.io/onesie/) and everything seems to be working correctly.
