### ISSUE TITLE
Add some style to Onesie

### ISSUE THREAD

**Issue by ohall** [GRT/onesie#24]
CSS and font improvements

**Comment by tjsampson** [comment]
@ohall & @yshen01 are either of you strongly opinionated (for or against) on style frameworks? I'm very familiar with Bootstrap and Material Design, but I wouldn't mind learning another one, if either of you have different preferences. 

[React-Bootstrap](https://react-bootstrap.github.io/support.html)
[React-toolbox](http://react-toolbox.com/#/)

**Comment by ohall** [comment]
@tjsampson no strong opinions. Tend to like material design, but like simplicity of implementation best.

**Comment by ohall** [comment]
I think we're good on this one.  Will capture any additional style refactoring in later stories
