### ISSUE TITLE
Footer Out of position

### ISSUE THREAD

**Issue by ohall** [GRT/onesie#61]
Long IP list causes footer to be out of position

pull latest `oo-static-server` to reproduce

![screen shot 2016-10-21 at 8 31 53 am](https://cloud.githubusercontent.com/assets/848113/19604156/f49cee4c-9768-11e6-8ae8-245a7bcebf22.png)

**Comment by yshen01** [comment]
I can take this one

**Comment by ohall** [comment]
@yshen01 👍

**Comment by yshen01** [comment]
Submitted PR for this issue here: https://github.com/GRT/onesie/pull/64
