### ISSUE TITLE
Truncate IP list in thumb view

### ISSUE THREAD

**Issue by ohall** [GRT/onesie#62]
I think we want to maintain shape for these thumbs.  Experiment with truncation and scrolling.

pull latest `oo-static-server` to reproduce

![screen shot 2016-10-21 at 8 36 20 am](https://cloud.githubusercontent.com/assets/848113/19604305/85e0d62a-9769-11e6-914f-c5044b5f8197.png)

**Comment by yshen01** [comment]
I'm going to take a crack at this one.
